### ISSUE TITLE
2 out of 3 cells in a table view not displaying the image(same image for all 3 cells)

### ISSUE THREAD

**Issue by yanko** [zalando/MapleBacon#11]
Hi,
I am having an issue where I have a tableview that can have many cells with same image.
for some reason only the first cell loads the image and the rest of the cells dont load the same image.
but if I had different images it would load them properly.

I can't seem to find what I am doing wrong here. please help. tx.

func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier(cellIdentifier, forIndexPath: indexPath) as! ProductCell
        let productBean:ProductBean = self.listOfSearchedProductsFilteredBySectionGroup[indexPath.row] as ProductBean
        cell.delegate = self

        if shouldDisplayStyleImage == "t" {
            let imageFullPath = "\(URLToImages)\(productBean.ImagePath)\(productBean.ImageName).\(productBean.ImageType)"            
            if let imageURL = NSURL(string: imageFullPath) {
                 cell.imgProductImg?.setImageWithURL(imageURL) {(_, error) in
                    log("pvc cell error:\(error)")
                    if error == nil {
                        let transition = CATransition()
                        cell.imgProductImg?.layer.addAnimation(transition, forKey: "fade")
                    }
                }

            }
            
        }
        
        return cell
    }

**Comment by ramy-kfoury** [comment]
Hi Yanko,

I just tried our example project with the same image, works fine. Feel free to try it out yourself

1 - Which version are you using? Is it the latest version of MapleBacon?
2 - What is the error being logged?

Thanks,

**Comment by yanko** [comment]
Hi Ramy,
I did try your examples and it works on my side too the only difference is I use a tableview but would not 
matter in this case.

1 - I used Cocoapods to pull the whatever version is there like this:
...
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
 
pod 'MapleBacon'
...
I will try to manually importing the latest version from github instead of pulling from cocoapods, and see if that fixes it.

2 - there are no error logs, when I search for the records, 3 come back all 3 having the same url,
and once I use the setImageWithUrl, it only shows first item with the image fade and show up,
the other 2 records don't show the image. and if I search again the same way, then it reloads all and
the images show up.

thank you.

**Comment by yanko** [comment]
Hi Ramy,
ok so I am able to reproduce the same effect in your example.
in the support files/imageURLs.plist, I remove everything but 3 same URLs:
    <string>http://i5.ztat.net/detail/DP/52/1C/08/DB/11/DP521C08D-B11@10.1.jpg</string>
    <string>http://i5.ztat.net/detail/DP/52/1C/08/DB/11/DP521C08D-B11@10.1.jpg</string>
    <string>http://i5.ztat.net/detail/DP/52/1C/08/DB/11/DP521C08D-B11@10.1.jpg</string>
I make sure to remove the MapleBaconExample app from the device, so that cached images are gone.
then I just reinstall the app, and only one image shows up, but I know there are 2 other records but you
only see empty space.... if you where to put a label in the image view it would show you that it does generate the other 2 records with no image...

I will investigate in the src code, but am new to ios swift world so if you have any idea,
please help!

thank you!

**Comment by JanGorman** [comment]
I an confirm that behaviour, I'm assuming that it's the `ImageManager` acting up because of the line

`completion?(ImageInstance(image: nil, state: .Downloading, url: nil), nil)` when you enqueue the same image URL

Because if you start the app again, the same image displays just fine from cache. What do you think, @ramy-kfoury ?

**Comment by ramy-kfoury** [comment]
Thanks @yanko. I will take a look and provide a fix soon

**Comment by ramy-kfoury** [comment]
Thanks @yanko for reporting
Fixed by [Pull Request #12](https://github.com/zalando/MapleBacon/pull/12)

**Comment by yanko** [comment]
Thank you so much!

p.s. do I need to do anything specific with cocoapod? I did "pod update" and it told me it pulled the 1.0.11
but when I check in the source code the code changes are not there yet... and if I test my app, it still does 
not work...
the example works when I get it from github...

**Comment by JanGorman** [comment]
@yanko Just pushed the update to CocoaPods too, if you `pod update` now you should get 1.0.12

**Comment by yanko** [comment]
Thank you! all good!
