### ISSUE TITLE
A placeholder image

### ISSUE THREAD

**Issue by tapz** [zalando/MapleBacon#17]
It would be nice to have a placeholder image while the actual image is loading. Like in SDWebImage. Also, if the placeholder is a preview image then a crossfade to the actual image when it's loaded.

**Comment by JanGorman** [comment]
Thanks for the suggestion. I have some time next week, will add this to the list of TODOs.

**Comment by winkelsdorf** [comment]
Thank you, great work!

**Comment by tapz** [comment]
Could the placeholder be displayed only when downloading a remote image not for locally cached images? Now the image does no appear immediately, but is crossfaded, even if it's immediately available from the cache. This causes kind of flickering when updating a tableview with images.
