### ISSUE TITLE
No such module: import MapleBacon 

### ISSUE THREAD

**Issue by yanko** [zalando/MapleBacon#24]
Hi there,
I just updated to latest ios 9 xcode 7.0.1 and os x El Capitan.
and pulled the latest MapleBacon from pods.

it no longer sees the MapleBacon as library.

help, please?

tx.

**Comment by JanGorman** [comment]
@yanko Sorry to hear that, I'll check this out some time later today

**Comment by JanGorman** [comment]
@yanko Which version of CocoaPods are you using? I tried with the current stable `0.38.2` and it works fine

**Comment by yanko** [comment]
@JanGorman same
vm-####:~ me$ pod --version
0.38.2

I will try again, will remove all the pods and do it from scratch.

Thank you. 

p.s. will let you know.

**Comment by yanko** [comment]
this is what I am getting... will need to research on it.

Target 'MapleBacon' of project 'Pods' was rejected as an implicit dependency for 'MapleBacon.framework' because its architectures 'x86_64' didn't contain all required architectures 'i386'

if by any chance you know about this let me know!

thank you.

**Comment by tapz** [comment]
Have you tried to set "Build Active Architecture Only" to NO for both the pods project and your app target?

**Comment by yanko** [comment]
@tapz thank you so much, that seemed to fix it!
@JanGorman thank you also!
