### ISSUE TITLE
cancelDownload in UIImageView extension public

### ISSUE THREAD

**Issue by tapz** [zalando/MapleBacon#27]
Could you make cancelDownload function in UIImageView extension public? Currently there is no way to cancel the download (e.g. for a recycled tableView cell). 

A better solution, which requires a bit more work would be not to cancel the download, but instead the downloaded image should not be set to the image view anymore (just put to the cache). E.g. a new function ignoreDownload() and a new "doNotCancelPreviousDownload" parameter to setImageWithURL.

**Comment by papertigers** [comment]
Thoughts on the following:

In my branch I currently modified the function to return an optional
```
public func setImageWithURL(url: NSURL, placeholder: UIImage? = nil, crossFadePlaceholder crossFade: Bool = true,
            cacheScaled: Bool = false, completion: ImageDownloaderCompletion? = nil) -> ImageDownloadOperation?
```

This way you can do:
operation = imageView.setImageWithURL(imageURL)
and in a reusable cell you can
cell.operation?.cancel()

**Comment by papertigers** [comment]
Or does the cancelDownload() already take care of this by setting self.operation = operation on the imageView?

**Comment by LappleApple** [comment]
@JanGorman Same question as for previous issue, re: @tapz's suggestion ...

**Comment by tapz** [comment]
Switched from MapleBacon to AlamofireImage...
