### ISSUE TITLE
Negative frameCount in animated GIF

### ISSUE THREAD

**Issue by tapz** [zalando/MapleBacon#28]
Some animated GIFs cause crash here. The frame count is -100 because gcd is -1 because delays[0] is -1. Other 9 delays are all +100.

fatal error: Can't form Range with end < start
```
extension UIImage {
    private class func framesFromImages(images: [CGImageRef], delays: [Int]) -> [UIImage] {
        let gcd = DivisionMath.greatestCommonDivisor(delays)
        var frames = [UIImage]()
        for i in 0..<images.count {
            let frame = UIImage(CGImage: images[Int(i)])
            let frameCount = Int(delays[Int(i)] / gcd)

            for _ in 0..<frameCount {  <----- EXC_BREAKPOINT
                frames.append(frame)
            }
        }
        return frames
    }
```

**Comment by JanGorman** [comment]
@tapz Do you have a sample gif to help debug this?

**Comment by tapz** [comment]
I think it was this one. When I added abs to frameCount= it didn't crash anymore and also the animation was displayed correcly.

![calvinandhobbesgifs2-1343699847](https://cloud.githubusercontent.com/assets/11726387/10870056/b98d1c0c-80c9-11e5-83d7-3cc56f34a74d.gif)

**Comment by JanGorman** [comment]
cool, thanks
