### ISSUE TITLE
Animated GIFs not always displayed

### ISSUE THREAD

**Issue by tapz** [zalando/MapleBacon#29]
The same animated GIF is sometimes displayed, sometimes not.

**Comment by LappleApple** [comment]
@tapz Not sure if you're still interested/using this project, but if so, would you be willing to try the bug fix and make a PR?

**Comment by tapz** [comment]
Switched from MapleBacon to AlamofireImage...

**Comment by LappleApple** [comment]
Thanks for the update, @tapz.
