### ISSUE TITLE
Is there a way to change the cached image and write this back to disk?

### ISSUE THREAD

**Issue by alombard** [zalando/MapleBacon#37]
My use case is one where I round profile images after they have loaded but doing so every time can be a bit performance intensive.  My ideal approach would be to do that work once and then save that (modified) asset to the cache for future reads.

Thanks in advance,

Andrew

**Comment by JanGorman** [comment]
Hey Andrew,

You should be able to achieve that by creating your own cache. MapleBacon comes with the `Storage` protocol that's passed a `UIImage` and is responsible for returning it again for matching URLs. The `downloadImage` sets the built in storage class as default parameter that you can override it with your own class: https://github.com/zalando/MapleBacon/blob/master/Library/MapleBacon/MapleBacon/ImageManager.swift#L18

Would that work?

**Comment by alombard** [comment]
Great!  That's exactly what I was looking for - I'll take a look at this and get back to you if I have any issues.
