### ISSUE TITLE
The first MapleBacon question on StackOverflow!

### ISSUE THREAD

**Issue by josephbeuysmum** [zalando/MapleBacon#38]
I was having difficulty with MapleBacon, so I went searching on StackOverflow. I was **amazed** to see this:

<img width="411" alt="screen shot 2016-10-21 at 11 57 10" src="https://cloud.githubusercontent.com/assets/14836799/19596246/987b5cbc-9785-11e6-80d6-4b323b1f37b5.png">

So of course I asked the question. If anyone could help, that would be great, thank you:

http://stackoverflow.com/questions/40175631/maplebacon-diskstorage-no-longer-granting-access-to-images-after-3-0-0-upgrade

**Comment by JanGorman** [comment]
This was indeed a genuine bug. 3.0.1 fixes that.

p.s. I'm so disturbed by your style of formatting and variable naming 😆

**Comment by josephbeuysmum** [comment]
The fix is working well over here, thanks for uploading it. Be disturbed. I prefer space and readability over the dense, headache-inducing vine-tangle of code favoured by developers coming over from Objective-C.
