### ISSUE TITLE
Different image url but show same image. :(

### ISSUE THREAD

**Issue by lmcmz** [zalando/MapleBacon#4]
I was change the image url string to test my image url but it seem there have some issue in your code.

test image url:

1. http://cdnq.duitang.com/uploads/item/201409/30/20140930170248_GsFv4.thumb.224_0.jpeg
2. http://cdnq.duitang.com/uploads/item/201410/14/20141014185925_FBQNS.thumb.224_0.jpeg
3. http://img5q.duitang.com/uploads/item/201411/06/20141106161920_MMNVv.thumb.224_0.jpeg

Those image url show the same picture. :(

![2015-04-30 8 24 55](https://cloud.githubusercontent.com/assets/9669733/7425483/22559c62-ef77-11e4-862a-5061edacdcfb.png)
![2015-04-30 8 24 43](https://cloud.githubusercontent.com/assets/9669733/7425484/25593658-ef77-11e4-9396-bcaaf322f8bf.png)

**Comment by lmcmz** [comment]
Every-time I reset my simulate then it show in correct way. :( Weird.

**Comment by JanGorman** [comment]
@lmcmz Thanks for reporting this – I just verified that the hashing function collides with these strings. I'll post a fix for this today.
