### ISSUE TITLE
Cancelling UIImageView extension crashes on nil task

### ISSUE THREAD

**Issue by tapz** [zalando/MapleBacon#9]
When rotating screen crashes with the UIImage extension for task being nil. Maybe you should make task optional and add a null check as the operation may not have even started (resumeDownload called) before cancel is called.

```
func cancelDownload() {
        operation?.cancel()
}

public override func cancel() {
        task.cancelByProducingResumeData { <-- CRASH HERE, task = nil
            [unowned self] data in
            self.resumeData = data
        }
}

**Comment by JanGorman** [comment]
Thanks for the report!
